//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYOD_manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BYOD
    {
        public string EQID { get; set; }
        public string MISID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string YearLevel { get; set; }
        public bool Approved { get; set; }
    }
}
